styles/datapads.css, styles/opening_crawl.css, templates/datapads_bounty.html
Addresses issue #68 by using `..` instead of `/modules/ffg-star-wars-enhancements/`
=> Fix relative urls

scripts/opening_crawl.js
=> Stop music after opening crawl window is closed

module.json, styles/settings.css
Add a scrollbar to animation settings.
Fixes #91
=> fix(animation): fix animation settings when viewed under low resolutions

ffg-star-wars-enhancements.js, lang/en.json, module.json, release-notes.md, scripts/stim_sync.js, scripts/talent_checker.js
Adds Stimpack usage as a status on tokens based on the stats tracked on the actor.
=> feat(stim_sync): add stimpack usage to tokens

lang/en.json, release-notes.md, scripts/controls_layer.js, scripts/hologram.js
Add functionality suggested [on reddit](https://www.reddit.com/r/Star_Wars_Maps/comments/skoqj6/foundry_token_magic_fx_holo_macro/).
=> feat(hologram): add token --> hologram convert

lang/en.json, release-notes.md, scripts/controls_layer.js, scripts/hologram.js, scripts/shop.js
ignore the other commit, I was so engrossed in `Shutter Island` that I forgot to rebase onto main first
=> Shop fixes

content/dice_helper.json, content/dice_helper_fr.json, scripts/dice_helper.js
Replacing & handling i18n skill names.
Searching if a dice_helper_LANG.json instead of generic one.
=> Translation handle for dice_helper

ffg-star-wars-enhancements.js, module.json, release-notes.md, scripts/animation.js, scripts/controls_layer.js, scripts/datapads.js, scripts/dice_helper.js, scripts/hologram.js, scripts/hyperspace.js, scripts/minionsize_sync.js, scripts/opening_crawl.js, scripts/rename.js, scripts/shop.js, scripts/shop_sheet.js, scripts/stim_sync.js, scripts/strain_reminder.js, scripts/talent_checker.js, scripts/util.js, scripts/vehicle_roller.js, templates/datapads_bounty.html
initial support for v10 Foundry.
only known issue is that the vehicle roller has been implemented natively in the system as well, meaning it can be retired from here.
=> Foundry v10

release-notes.md, scripts/animation.js, scripts/settings.js, templates/configure_attack_animations.html
=> fix(attack): Foundry v10 support

.gitignore, cypress/README.md, data/.gitignore, docker-compose.yaml, secrets.json.dist
=> chore(docker): Add docker compose configuration and documentation

.github/workflows/cypress-impl.yaml
=> chore(actions): Cache FoundryVTT container even on failure

.github/workflows/main.yml, release-notes.md
=> fix(build): Add missing test files to module release build

scripts/minionsize_sync.js
=> fix(minions): correct minion group icons

release-notes.md
=> docs(release): update release notes

scripts/talent_checker.js
* disable talent checker and minion size checkers by default (these are now implemented in the system)
closes #187
=> refactor(settings): update defaults

module.json
=> chore(dependencies): add jb2a as an optional dependency

ffg-star-wars-enhancements.js, release-notes.md, scripts/animation.js, scripts/dice_helper.js
* fix alignment with non-english systems
* fix await bug for dice
#182
=> fix(animations): alignment

scripts/shop.js, scripts/shop_sheet.js
* defaults to a comma seperated string and splits it into an array
=> fix(shop): fix shop compendium searching

release-notes.md, scripts/talent_checker.js
* use new ActiveEffectCounter instead of EffectCounter
#200
=> fix(status): status icons work again

release-notes.md, templates/configure_custom_attack_animations.html
* fix `items` not being properly initialized/reset
#206
=> fix(animation): item name animation configuration

release-notes.md, scripts/shop_sheet.js
* fixes default compendium names to match the updated system names
#213
=> fix(shop): correct compendiums

module.json, release-notes.md
* update README with 3rd party PR
* prep for 2.1.2 release
=> chore(release): prep for 2.1.2 release
